spring.application.name=assetpulse

# MongoDB Connection
spring.data.mongodb.uri=${MONGODB_URI}

# Optional (for debugging)
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG

app.frontend.url=https://asset-pulse-tan.vercel.app
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
server.port=${PORT:8080}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true
