spring.application.name=assetpulse

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/assetpulse

# Optional (for debugging)
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
